from time import sleep
class Game:
    def __init__(self):
        sleep(1)
        print('\n\n\nWelcome to Rock Paper Scissors Lizard Spock.')
        sleep(1)
        print('\nEach match will be best of three games \nUse the number keys to enter your selection\n')
        sleep(1)
        print('Rock crushes Scissors')
        sleep(1)
        print('Scissors cuts Paper')
        sleep(1)
        print('Paper covers Rock')
        sleep(1)
        print('Rock crushes Lizard')
        sleep(1)
        print('Lizard poisons Spock')
        sleep(1)
        print('Spock smashes Scissors')
        sleep(1)
        print('Scissors decapitates Lizard')
        sleep(1)
        print('Lizard eats Paper')
        sleep(1)
        print('Paper disproves Spock')
        sleep(1)
        print('SPock vaporizes Rock')